### ISSUE TITLE
PivotGrid and its selector not binding/working properly

### ISSUE THREAD

**Issue by snkrishnan1** [IgniteUI/igniteui-angular2#203] opened 2017-09-28 18:44 UTC
I have developed an application with Angular2, IgniteUI/Infragistics PivotGrid control to load the PivotGrid. We are passing the Cubes information i.e Measures/Dimensions dynamically and binding the json data with the PivotGrid. We are using the Angular2 wrapper component given by the IgniteUI/Infragistics in their github demo.

A breif explaination here about my application:-

Workbook is the parent component which has dropdown. Onchange event of the dropdown would trigger the PivotGrid component which is a child component of Workbook component, to load and bind the PivotGrid. After the PivotGrid grid is bound/loaded, it should load the selector for the PivotGrid. this selector is placed in a child component called slideout under this PivotGrid. Basically whenever the dropdown is getting changed, it should load the appropriate PivotGrid and its selector components respectively.

In Workbook which is the parent component has dropdown, "OnChange" event trigger when the dropdown value changes, it is going to trigger the ngOnChanges event in the PivotGrid since its Input() parameters values is being changed.
In PivotGrid during ngOnChanges event, it calls the local method LoadInfraPivotGrid() which binds the grid. After binding the grid, I change the Input() parameters value for the slideout component which should again trigger ngOnChanges event in slideout component.
In slideout during ngOnChanges event it binds the selector component.
the Data to bind the selector component is passed from the parent PivotGrid using the @Injectable component SessionService which hold the data. The values are read from this SessionService and then bind with the selector.
The Problem I am facing here is data is not properly bound/loaded with the PivotGrid/Selector. The result is whenever I try to change the Measures/Dimensions in the selector, the PivotGrid crashes with the following error message. When I try change/modify in the selector control continuously this problem would occur.

The sample code for my application can be found in [link](https://github.com/snkrishnan1/PivotGridSample)

I did the suggested changes in some other forum by adding the 
`this.gridId = "pivotGrid"; `
in the constructor. 
The error/exception which I am getting can be reproduced in the sample code from URL itself. Steps to replicate the issue:-

1. Please open the "Report3" from the dropdown, Report3 gets loaded
2. Drag-Drop the "Vendor" from "Item Scorecard" to Columns (Please refer snapshot)
3. Drag-Drop "Retailer" to "Rows" The grid crashes immediately after this.

   ```
 Uncaught TypeError: Cannot read property 'key' of undefined
        at t.(anonymous function).(anonymous function)._transformGridData (http://localhost:3000/js/IgniteUI/infragistics.lob.js:661:23266)
        at t.(anonymous function).(anonymous function)._transformGridData (http://code.jquery.com/ui/1.10.3/jquery-ui.min.js:5:5028)
        at t.(anonymous function).(anonymous function)._configureOptions (http://localhost:3000/js/IgniteUI/infragistics.lob.js:661:12632)
        at t.(anonymous function).(anonymous function)._configureOptions (http://code.jquery.com/ui/1.10.3/jquery-ui.min.js:5:5028)
        at t.(anonymous function).(anonymous function)._onGridUpdated (http://localhost:3000/js/IgniteUI/infragistics.lob.js:661:26768)
        at t.(anonymous function).(anonymous function)._onGridUpdated (http://code.jquery.com/ui/1.10.3/jquery-ui.min.js:5:5028)
        at Class.<anonymous> (http://localhost:3000/js/IgniteUI/infragistics.lob.js:661:9410)
        at Class.dispatch (http://code.jquery.com/jquery-1.12.3.js:5226:27)
        at Class.elemData.handle (http://code.jquery.com/jquery-1.12.3.js:4878:28)
        at Object.trigger (http://code.jquery.com/jquery-1.12.3.js:5130:12)
```

**Comment by dkamburov** [comment] 2017-11-10 10:50
This is either a data configuration issue, or an issue with the pivot grid itself. I'm almost certain it will reproduce in non-angular scenario. I'll need to do further investigation to see what's causing it.

**Comment by MayaKirova** [comment] 2017-12-01 12:43
I see that you’ve logged a case in our support system at Infragistics.com with number:
CAS-187611-W1Q7J4
Which seems to be the same as this one.


That case seems to have been resolved a while ago. Here’s a summary of the solution to the issue from the case:

“
The reason for this issue, and the exception when changing dimensions is due to trying to expand a tuple that cannot be expanded.  You are calling this in the dataSourceInitialized event handler for the InfraPivotGrid component.

You can add a check before calling it with the following code and it should prevent these two issues.


dataSourceInitialized: function (evt, ui) {
    var isExpandable = ui.dataSource.result().axes().item(0).tuples().item(0).members().item(0).isExpandable();
    if(isExpandable){
        ui.owner.expandTupleMember("rowAxis", 0, 0, true);
    }
}
“

Since the issue seems to have been resolved via the case I’m closing this one as well. If you have any additional questions feel free to reopen it.

**Closed by MayaKirova** 2017-12-01 12:43 UTC
Labels: answered
